default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV.fetch("POSTGRES_USER", "postgres") %>
  password: <%= ENV.fetch("POSTGRES_PASSWORD", "postgres") %>
  host: <%= ENV.fetch("POSTGRES_HOST", "localhost") %>

development:
  <<: *default
  database: model_houses_development

test:
  <<: *default
  database: model_houses_test

production:
  primary: &primary_production
    <<: *default
    database: model_houses_production
    username: model_houses
    password: <%= ENV["MODEL_HOUSES_DATABASE_PASSWORD"] %>
  cache:
    <<: *primary_production
    database: model_houses_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: model_houses_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: model_houses_production_cable
    migrations_paths: db/cable_migrate
